# Generated by Django 5.2.8 on 2025-11-23 02:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.AlterField(
            model_name='partner',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
