# Generated by Django 5.2.8 on 2025-11-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_equipemember_mission_news_professionalarea_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipeMember',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='ProfessionalArea',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
