# Generated by Django 5.2.8 on 2025-11-23 02:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_partner_options_alter_partner_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='Nom (FR)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, help_text="Partner's official website link", null=True),
        ),
    ]
