# Generated by Django 5.2.8 on 2025-11-24 23:43

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_equipemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (EN)')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('target_group', models.CharField(choices=[('companies', 'Entreprises / Projet R&D'), ('points_of_sale', 'Points de vente (Superette, Boutique, Grande surface)'), ('distributors', 'Distributeurs (Grossiste)')], default='companies', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Area',
                'verbose_name_plural': 'Professional Areas',
                'ordering': ['name_fr'],
            },
        ),
    ]
