# Generated by Django 5.2.8 on 2025-11-25 23:23

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_recipesardine_recipethon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SardineRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sardine_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sardine Recipe',
                'verbose_name_plural': 'Sardine Recipes',
                'ordering': ['title_fr'],
            },
        ),
        migrations.DeleteModel(
            name='RecipeSardine',
        ),
        migrations.DeleteModel(
            name='RecipeThon',
        ),
    ]
