# Generated by Django 5.2.8 on 2025-11-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_sardinerecipe_delete_recipesardine_delete_recipethon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sardinerecipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sardine Recipe', 'verbose_name_plural': 'Sardine Recipes'},
        ),
    ]
