# Generated by Django 5.2.8 on 2025-11-26 00:50

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_alter_sardinerecipe_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThonRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thonrecipe_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thon Recipe',
                'verbose_name_plural': 'Thon Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
