# Generated by Django 5.2.8 on 2025-11-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_thonproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('commentaire', 'Commentaires et suggestions'), ('question', 'Questions générales'), ('support', 'Support technique'), ('partenariat', 'Partenariat')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
