# Generated by Django 5.2.8 on 2025-11-26 04:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (EN)')),
                ('description_fr', models.TextField(verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Page d'accueil",
                'verbose_name_plural': "Pages d'accueil",
                'ordering': ['-created_at'],
            },
        ),
    ]
