# Generated by Django 5.2.8 on 2025-11-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0019_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
