# Generated by Django 5.2.8 on 2025-11-29 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Base.partner')),
            ],
            options={
                'verbose_name': 'Historique de statut partenaire',
                'verbose_name_plural': 'Historique des statuts partenaires',
                'ordering': ['-changed_at'],
            },
        ),
    ]
