# Generated by Django 5.2.8 on 2025-11-29 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0022_partnerstatushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerstatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Partner Status History', 'verbose_name_plural': 'Partner Status Histories'},
        ),
        migrations.AlterField(
            model_name='partnerstatushistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partnerstatushistory',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Base.partner'),
        ),
    ]
