# Generated by Django 5.2.8 on 2025-12-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0023_alter_partnerstatushistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thonproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
