# Generated by Django 5.2.8 on 2025-12-14 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0024_remove_thonproduct_image_thonproduct_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thonproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
