# Generated by Django 5.2.8 on 2025-12-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0025_remove_thonproduct_image_url_thonproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalarea',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Zone active'),
        ),
    ]
