# Generated by Django 5.2.8 on 2026-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0026_professionalarea_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='content_fr',
        ),
        migrations.AddField(
            model_name='mission',
            name='content_mission_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content Mission (EN)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='content_mission_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu Mission (FR)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='content_valeur_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content Value (EN)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='content_valeur_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu Valeur (FR)'),
        ),
    ]
