# Generated by Django 5.2.8 on 2026-04-04 14:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0027_remove_mission_content_en_remove_mission_content_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('title2_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('title3_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('title4_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('title5_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('title1_en', models.CharField(blank=True, max_length=30, null=True)),
                ('title2_en', models.CharField(blank=True, max_length=30, null=True)),
                ('title3_en', models.CharField(blank=True, max_length=30, null=True)),
                ('title4_en', models.CharField(blank=True, max_length=30, null=True)),
                ('title5_en', models.CharField(blank=True, max_length=30, null=True)),
                ('content1_fr', models.TextField(blank=True, null=True)),
                ('content2_fr', models.TextField(blank=True, null=True)),
                ('content3_fr', models.TextField(blank=True, null=True)),
                ('content4_fr', models.TextField(blank=True, null=True)),
                ('content5_fr', models.TextField(blank=True, null=True)),
                ('content1_en', models.TextField(blank=True, null=True)),
                ('content2_en', models.TextField(blank=True, null=True)),
                ('content3_en', models.TextField(blank=True, null=True)),
                ('content4_en', models.TextField(blank=True, null=True)),
                ('content5_en', models.TextField(blank=True, null=True)),
                ('image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('image_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
            ],
        ),
    ]
