# Generated by Django 5.2.8 on 2026-04-17 11:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0028_recherche'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitaineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capitaine Product',
                'verbose_name_plural': 'Capitaine Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
