# Generated by Django 5.2.8 on 2026-05-05 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0030_recherchepartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('poste', models.CharField(blank=True, max_length=200, null=True)),
                ('sujet', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
