# Generated by Django 5.2.8 on 2026-05-09 11:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0031_contactprofessionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sardineproduct',
            name='image_recette1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='image_recette2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredient_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredient_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sardineproduct',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sardineproduct',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
