# Generated by Django 5.2.8 on 2026-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0032_sardineproduct_image_recette1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredientcontent1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredientcontent1_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredientcontent2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredientcontent2_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredientcontent3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredientcontent3_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredienttitle1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredienttitle1_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredienttitle2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredienttitle2_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredienttitle3_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='ingredienttitle3_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
