# Generated by Django 5.2.8 on 2026-05-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0033_sardineproduct_ingredientcontent1_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sardineproduct',
            old_name='ingredientcontent1_en',
            new_name='ingredientcontent_en',
        ),
        migrations.RenameField(
            model_name='sardineproduct',
            old_name='ingredientcontent1_fr',
            new_name='ingredientcontent_fr',
        ),
        migrations.RemoveField(
            model_name='sardineproduct',
            name='ingredientcontent2_en',
        ),
        migrations.RemoveField(
            model_name='sardineproduct',
            name='ingredientcontent2_fr',
        ),
        migrations.RemoveField(
            model_name='sardineproduct',
            name='ingredientcontent3_en',
        ),
        migrations.RemoveField(
            model_name='sardineproduct',
            name='ingredientcontent3_fr',
        ),
    ]
