# Generated by Django 5.2.8 on 2026-05-11 11:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0034_rename_ingredientcontent1_en_sardineproduct_ingredientcontent_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Image'),
        ),
    ]
