# Generated by Django 5.2.8 on 2026-06-10 12:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0035_mission_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GammePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Titre (EN)')),
                ('descriptionstitle_fr', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre de la section (FR)')),
                ('descriptionstitle_en', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre de la section (EN)')),
                ('descriptionstatinale_fr', models.TextField(verbose_name='Description Tartinables (FR)')),
                ('descriptionstatinale_en', models.TextField(blank=True, verbose_name='Description Tartinables (EN)')),
                ('descriptionsSauces_fr', models.TextField(verbose_name='Description Sauces (FR)')),
                ('descriptionsSauces_en', models.TextField(blank=True, verbose_name='Description Sauces (EN)')),
                ('imagecoverproduct', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de couverture (hero)')),
                ('image_tartinable', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image Tartinables')),
                ('image_sauce', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image Sauces')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Gammes',
                'verbose_name_plural': 'Pages Gammes',
                'ordering': ['-created_at'],
            },
        ),
    ]
