# Generated by Django 5.2.8 on 2026-06-10 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0036_gammepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammepage',
            name='image_poisson',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image poisson central'),
        ),
    ]
