# Generated by Django 5.2.8 on 2026-06-11 12:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0037_gammepage_image_poisson'),
    ]

    operations = [
        migrations.CreateModel(
            name='RillettePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Titre (EN)')),
                ('descriptionstitle_fr', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre (FR)')),
                ('descriptionstitle_en', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre (EN)')),
                ('sardinetitle_fr', models.CharField(blank=True, max_length=255, verbose_name='Titre Sardine (FR)')),
                ('sardinetitle_en', models.CharField(blank=True, max_length=255, verbose_name='Titre Sardine (EN)')),
                ('thontitle_fr', models.CharField(blank=True, max_length=255, verbose_name='Titre Thon (FR)')),
                ('thontitle_en', models.CharField(blank=True, max_length=255, verbose_name='Titre Thon (EN)')),
                ('capitainetitle_fr', models.CharField(blank=True, max_length=255, verbose_name='Titre Capitaine (FR)')),
                ('capitainetitle_en', models.CharField(blank=True, max_length=255, verbose_name='Titre Capitaine (EN)')),
                ('descriptionssardinerillette_fr', models.TextField(blank=True, verbose_name='Description Sardine (FR)')),
                ('descriptionssardinerillette_en', models.TextField(blank=True, verbose_name='Description Sardine (EN)')),
                ('descriptionsthonrillette_fr', models.TextField(blank=True, verbose_name='Description Thon (FR)')),
                ('descriptionsthonrillette_en', models.TextField(blank=True, verbose_name='Description Thon (EN)')),
                ('descriptionscapitainerillette_fr', models.TextField(blank=True, verbose_name='Description Capitaine (FR)')),
                ('descriptionscapitainerillette_en', models.TextField(blank=True, verbose_name='Description Capitaine (EN)')),
                ('imagecoverrillette', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de couverture (hero)')),
                ('image_sardine', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image Sardine')),
                ('image_thon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image Thon')),
                ('image_capitaine', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image Capitaine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Rillettes',
                'verbose_name_plural': 'Pages Rillettes',
                'ordering': ['-created_at'],
            },
        ),
    ]
