# Generated by Django 5.2.8 on 2026-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0038_rillettepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sardineproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit Sardine', 'verbose_name_plural': 'Produits Sardine'},
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='caracteristique_en',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristique (EN)'),
        ),
        migrations.AddField(
            model_name='sardineproduct',
            name='caracteristique_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristique (FR)'),
        ),
    ]
