# Generated by Django 5.2.8 on 2026-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0039_alter_sardineproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('commentaire', 'Commentaires et suggestions'), ('question', 'Questions générales'), ('support', 'Support technique'), ('partenariat', 'Partenariat'), ('distributeur', 'Distributeur')], max_length=50),
        ),
    ]
