# Generated by Django 5.2.8 on 2026-06-20 03:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0040_alter_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitaineproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit Capitaine', 'verbose_name_plural': 'Produits Capitaine'},
        ),
        migrations.AlterModelOptions(
            name='thonproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit Thon', 'verbose_name_plural': 'Produits Thon'},
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='caracteristique_en',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristique (EN)'),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='caracteristique_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristique (FR)'),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='image_recette1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='image_recette2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredient_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredient_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredientcontent_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredientcontent_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredienttitle1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredienttitle1_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredienttitle2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredienttitle2_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredienttitle3_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capitaineproduct',
            name='ingredienttitle3_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='caracteristique_en',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristique (EN)'),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='caracteristique_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristique (FR)'),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='image_recette1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='image_recette2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredient_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredient_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredientcontent_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredientcontent_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredienttitle1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredienttitle1_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredienttitle2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredienttitle2_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredienttitle3_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thonproduct',
            name='ingredienttitle3_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitaineproduct',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capitaineproduct',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thonproduct',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thonproduct',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
